require('plugin_setups.bufferline')
require('plugin_setups.nvimtree')
require('plugin_setups.telescope')
require('plugin_setups.cmake')
require('plugin_setups.dapui')
require('plugin_setups.winbar')
require('plugin_setups.neogen')
require('plugin_setups.rust')
