require('plugin_setups.whichkey')
require('plugin_setups.treesitter')
require('plugin_setups.bufferline')
require('plugin_setups.nvimtree')
require('plugin_setups.telescope')
-- require('plugin_setups.cmake')
-- require('plugin_setups.dapui')
-- require('plugin_setups.comment')
require('plugin_setups.winbar')
